matrix:
  include:
    - os: linux
      language: c
      dist: xenial
      sudo: required

addons:
  apt:
    sources:
      - sourceline: 'ppa:vriviere/ppa'
    packages:
      - binutils-m68k-atari-mint
      - gcc-m68k-atari-mint
      - mintbin-m68k-atari-mint

branches:
  only:
    - master

compiler:
  - gcc

env:
  global:
    - MAKEFLAGS="-j 2"
    - BINTRAY_USER="th-otto"
    # BINTRAY_API_KEY is defined in Travis Settings of freemint/cops
    - BINTRAY_REPO=teradesk-files

before_install:
  - .travis/install_ssh_id.sh
  - unset SSH_ID
  - .travis/install_prerequisities.sh

before_script:
  - . ./.travis/setup_env.sh

script:
  - . ./.travis/build.sh

deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy.sh
